name: Generate Snake
on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Manual trigger
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repo
      - uses: actions/checkout@v4

      # Generate the snake GIF and SVG
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: YOUR_USERNAME # Replace with your username
          gif_out_path: dist/snake.gif
          svg_out_path: dist/snake.svg

      # Commit and push the files to the output branch
      - name: Push to output branch
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git checkout -b output || git checkout output
          mkdir -p dist
          mv dist/snake.gif dist/snake.svg .
          git add snake.gif snake.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push origin output --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
